#ifndef MALIIT_KEYBOARD_LIB_COMMON
#define MALIIT_KEYBOARD_LIB_COMMON

#ifdef MALIIT_KEYBOARD_LIB_BUILDING
# define MALIIT_KEYBOARD_LIBRARY Q_DECL_EXPORT
#else
# define MALIIT_KEYBOARD_LIBRARY Q_DECL_IMPORT
#endif

#endif // COMMON