#ifndef MALIIT_KEYBOARD_PLUGIN_COMMON
#define MALIIT_KEYBOARD_PLUGIN_COMMON

#ifdef MALIIT_KEYBOARD_PLUGIN_LIB_BUILDING
# define MALIIT_KEYBOARD_PLUGIN_LIBRARY Q_DECL_EXPORT
#else
# define MALIIT_KEYBOARD_PLUGIN_LIBRARY Q_DECL_IMPORT
#endif

#endif // COMMON